Name: {{name}}
Method: {{upstream}}
Config: Acquire::Https::Proxy={{proxy}}
Suite: {{suite}}
GetInRelease: no
OmitExtraSourceOnly: no
VerifyRelease: {{verifyrelease}}
{% if filterformula %}FilterFormula: {{filterformula}}{% endif %}

